### ISSUE TITLE
Cloud I just segment and track interested object with prompt?

### ISSUE THREAD

**Issue by aixiaodewugege** [z-x-yang/Segment-and-Track-Anything#7]
Is it convenient to use GroundingDINO to provide bbox and do next step with your current code?

**Comment by aixiaodewugege** [comment]
Thanks for your reply. I have impleaded it myself, based on your code.

I am curious that which on have the better performance on tracking task, your method or the MOTRv2?

**Comment by z-x-yang** [comment]
"Segment and Track Anything" aims to achieve open-world video object segmentation, requiring the algorithm to have the ability to generalize to untrained object categories. In contrast, MOTR is designed for MOT tasks, which usually only detect and track specific targets (usually people and vehicles) and do not consider generalization capabilities. Furthermore, MOTR uses a BBox-based solution instead of a segmentation-based solution for tracking, which may reduce tracking performance.

In the VOT2022 challenge, our segmentation-based tracking method, based on AOT, significantly outperformed all BBox-based methods in robustness (detailed in the [Workshop presentation](https://data.votchallenge.net/vot2022/vot2022_st_rt.pdf)). This is a new breakthrough for segmentation-based methods and deserves further research and consideration.

**Comment by aixiaodewugege** [comment]
Thanks for your clearly response! 

Your current code is able to track every each segment generated by SAM, but SAM need bbox to generate better result. Hopes you can add detection model into your code.

Again thanks for your patience.

**Comment by ZillaRU** [comment]
> "Segment and Track Anything" aims to achieve open-world video object segmentation, requiring the algorithm to have the ability to generalize to untrained object categories. In contrast, MOTR is designed for MOT tasks, which usually only detect and track specific targets (usually people and vehicles) and do not consider generalization capabilities. Furthermore, MOTR uses a BBox-based solution instead of a segmentation-based solution for tracking, which may reduce tracking performance.
> 
> In the VOT2022 challenge, our segmentation-based tracking method, based on AOT, significantly outperformed all BBox-based methods in robustness (detailed in the [Workshop presentation](https://data.votchallenge.net/vot2022/vot2022_st_rt.pdf) shown below). This is a new breakthrough for segmentation-based methods and deserves further research and consideration.
> 
> <img alt="截屏2023-04-21 17 02 26" width="1268" src="https://user-images.githubusercontent.com/57658428/233594660-0720b6bf-f943-484d-9e0d-b4c54569997d.png">
> 
> <img alt="截屏2023-04-21 17 02 16" width="1272" src="https://user-images.githubusercontent.com/57658428/233594689-e0d7e2e3-2c50-4329-8f53-acecc09cef5b.png">

I am a beginner of CV😀. I wonder if there is a model combining semantic segmentation and segmentation-based tracking together. Or does your proposed AOT run fast enough to serve as a module of such a model (for video annotation)?
Thanks for your patience.

**Comment by z-x-yang** [comment]
> Thanks for your clearly response!
> 
> I noticed that you use first frame to generate better result. Could you please explain how does it work?
> 
> Your current code is able to track every each segment generated by SAM, but SAM need bbox to generate better result. Hopes you can add detection model into your code.
> 
> Again thanks for your patience.

The first frame is a reference frame, in which the objects are given. There could be more than one "first frame" since new objects may appear at different times. SAM-Track uses SAM to detect new objects per N frames.

Currently, we have released a new version to support interactive segmentation by click or brush (similar to BBox). We are considering adding the support of detection models to provide BBox prompts in a future version.

**Comment by z-x-yang** [comment]
> > "Segment and Track Anything" aims to achieve open-world video object segmentation, requiring the algorithm to have the ability to generalize to untrained object categories. In contrast, MOTR is designed for MOT tasks, which usually only detect and track specific targets (usually people and vehicles) and do not consider generalization capabilities. Furthermore, MOTR uses a BBox-based solution instead of a segmentation-based solution for tracking, which may reduce tracking performance.
> > In the VOT2022 challenge, our segmentation-based tracking method, based on AOT, significantly outperformed all BBox-based methods in robustness (detailed in the [Workshop presentation](https://data.votchallenge.net/vot2022/vot2022_st_rt.pdf) shown below). This is a new breakthrough for segmentation-based methods and deserves further research and consideration.
> > <img alt="截屏2023-04-21 17 02 26" width="1268" src="https://user-images.githubusercontent.com/57658428/233594660-0720b6bf-f943-484d-9e0d-b4c54569997d.png">
> > <img alt="截屏2023-04-21 17 02 16" width="1272" src="https://user-images.githubusercontent.com/57658428/233594689-e0d7e2e3-2c50-4329-8f53-acecc09cef5b.png">
> 
> I am a beginner of CV😀. I wonder if there is a model combining semantic segmentation and segmentation-based tracking together. Or does your proposed MS_AOT run fast enough to serve as a module of such a model (for video annotation)? Thanks for your patience.

The task you are talking about is similar to video semantic segmentation or video panoptic segmentation, for which our lab has released two large-scale datasets, [VSPW](https://github.com/sssdddwww2/CVPR2021_VSPW_Implement) and [VIPSeg](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset). 

When annotating these datasets, only 1 of 15 frames are required to be manually annotated since we can use our AOT framework to propagate annotations to all the other frames. In such short-term annotation scenes, our latest DeAOT models can simultaneously process 10 objects in real time and predict results comparable to human annotations.

**Comment by ZillaRU** [comment]
> > Thanks for your clearly response!
> > I noticed that you use first frame to generate better result. Could you please explain how does it work?
> > Your current code is able to track every each segment generated by SAM, but SAM need bbox to generate better result. Hopes you can add detection model into your code.
> > Again thanks for your patience.
> 
> The first frame is a reference frame, in which the objects are given. There could be more than one "first frame" since new objects may appear at different times. SAM-Track uses SAM to detect new objects per N frames.
> 
> Currently, we have released a new version to support interactive segmentation by click or brush (similar to BBox). We are considering adding the support of detection models to provide BBox prompts in a future version.

I was coding for using bbox as prompt to refine our dataset annotations when I saw your reply. ORZZZZZ.

**Comment by yamy-cheng** [comment]
> Is it convenient to use GroundingDINO to provide bbox and do next step with your current code?

Hi, the current version of our WebUI has integrated Grounding-DINO. You can use it according to the [tutorial](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/tutorial/tutorial%20for%20WebUI-1.5-Version.md).

**Comment by aixiaodewugege** [comment]
You guys are great!

I would like to ask how image segmentation-based tracking methods solve the problem of temporal consistency in segmentation in videos? If the segmentation results of the same object vary greatly between different frames, would it affect the tracking results?

**Comment by aixiaodewugege** [comment]
> 

Thanks for your reply.

You don't use the shape or the appearance of the object to do tracking? So AOT only use the position of the segmentations between frames to match the object?

**Comment by yamy-cheng** [comment]
> > 
> 
> Thanks for your reply.
> 
> You don't use the shape or the appearance of the object to do tracking? So AOT only use the position of the segmentations between frames to match the object?

AoT use hierarchal long-short-term transformer to propagate the masks between frames to get results.You can find more details about how AoT tracks objects in the [paper](https://arxiv.org/pdf/2106.02638.pdf).

**Comment by aixiaodewugege** [comment]
Thanks for your reply. I think you miss my meaning in temporal consistency. You can have a look at this page 
[https://zhuanlan.zhihu.com/p/554572973](https://zhuanlan.zhihu.com/p/554572973) .

I have tried your work in my scene, and I found that it will make mistake on big static objects, because of the bad temporal consistency for segmentation method. We can discuss more about it ,if you have time please contact me through my email and I will send your my video.
