### ISSUE TITLE
webUI keep showing error

### ISSUE THREAD

**Issue by richardliu1111** [z-x-yang/Segment-and-Track-Anything#75]
I used the colab notebook and successfully opened public url. However, after I have uploaded the video, it keeps showing error in "segment result of first page" block, "predicted video" block, and "predicted mask" block.

**Comment by LiNO3Dy** [comment]
Thank you for your question. To better assist you in resolving the issue, I need to view the error messages in the console.

**Comment by PhilisterD** [comment]
Same error

**Comment by jamyriver** [comment]
Same，HELP！

**Comment by yamy-cheng** [comment]
hi, This issue occurs because `SegTracker` has not been initialized. You need to click or select the object to be tracked in order to initialize SegTracker, just like the [tutorial](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/tutorial/tutorial%20for%20WebUI-1.0-Version.md) demonstrated.
